### ISSUE TITLE
Task Row 15 - Wrong Text 

### ISSUE THREAD

**Issue by m3ssij3ssi** [acidjazz/waa#197]
Wrong text. Replace current text with the following:

The U.S. needs to build 4.3 million more apartments by 2035 to meet the demand for rental housing. This includes 600,000 units (total) to fill the shortage from underbuilding after the 2008 financial crisis. 

The apartment industry stands ready to work with urban, suburban and rural communities in every region to meet the housing demand of Americans across all income levels.

![ourvisiondeamnd](https://user-images.githubusercontent.com/47862779/176790041-95d225df-ac6c-4ab5-affa-836762b3a72f.PNG)

**Comment by acidjazz** [comment]
@m3ssij3ssi is this copy the updated copy? call me crazy but I cannot see any difference

**Comment by m3ssij3ssi** [comment]
okay **I was crazy**. not sure what i was thinking. Sorry! let's close this one out! it looks good on staging

**Comment by m3ssij3ssi** [comment]
looks like i can close this myself. so closing!
