### ISSUE TITLE
Taks Row 16/17: Text needs updating, Remove extra text, chart question

### ISSUE THREAD

**Issue by m3ssij3ssi** [acidjazz/waa#198]
A couple things here, 
**1)  The text in the screenshot below - replace the text with:** 
The supply shortage has led to an increasing number of renter households who are paying more than they can afford. The total share of cost-burdened apartment households (those paying more than thirty percent of their income on housing) increased steadily from 42 percent in 1985 to 55 percent in 2019.

![image](https://user-images.githubusercontent.com/47862779/176790497-9c3b55f1-23c9-46e9-ba6e-bf2455149cfd.png)

**2) Remove the # of new apartment households a year... text** 
![image](https://user-images.githubusercontent.com/47862779/176790644-467412d9-8b45-4adc-9b32-8a1f89a85715.png)

3) Thanks for updating the charts to go to 2019 data! Can we make sure the label shows for the last year - 2019? In the current live site it shows 4 years (up to 2015). So can we make sure it shows 2019?

![image](https://user-images.githubusercontent.com/47862779/176790820-2245293b-995c-4385-85eb-f6c70872895d.png)

**Comment by acidjazz** [comment]
for 3. - i tried upping the ticks from 3 to 5, 8, 9, i still cant get it to show the last tick - i can look into this more though 
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/967369/176944310-9527cdf0-c396-455e-bb98-5bcf13870cbd.png">

**Comment by m3ssij3ssi** [comment]
Sorry it looks like I missed an edit. 
For this chart (the one on the left) -the Medium Apartment Income headline -  the text needs to be changed to this:

Rental housing has gotten more expensive to build and operate. At the same time, stagnant incomes have made it harder for people to pay for housing. In 2019 dollars, the median income of an apartment household has risen only marginally since 1985.
 
![image](https://user-images.githubusercontent.com/47862779/176951588-486b1daf-5f94-4eb6-aa3b-e297ae7c140a.png)

**Comment by m3ssij3ssi** [comment]
Regarding the chart years - i actually like what you have in your screen shot. going to 2017. That's fine. I just did the math and we would need to do every two years to end at 2010 starting from 1985 and that's too many ticks. I think what you have in your screen shot -every four years ending at 2017 works great.
