### ISSUE TITLE
metadata

### ISSUE THREAD

**Issue by acidjazz** [acidjazz/waa#20]
* 1000x1000 image to generate favicon
* 1200x630 image for sharing on social media
* title and description for all the google/facebook/twitter meta tags

**Comment by ToddRice** [comment]
Here is the 1000x1000 and the FB one 1200x630
![ico_1000x](https://cloud.githubusercontent.com/assets/20032549/26515622/0f815ac0-4242-11e7-94a1-7f83c47fec99.png)
![fb](https://cloud.githubusercontent.com/assets/20032549/26515623/0f86eeb8-4242-11e7-9768-b8d40495ba03.png)

**Comment by acidjazz** [comment]
![share](https://cloud.githubusercontent.com/assets/967369/26515856/c8b9fc72-4233-11e7-8798-8310f10c548c.png)
