### ISSUE TITLE
Resources section refactoring

### ISSUE THREAD

**Issue by acidjazz** [acidjazz/waa#203]
Our Vision (soon to be renamed Our Resources) page  - Publications Section: 

1) Combine the text in this box into the We Can Do This Section  (see screen shot in B18 for idea) 

2) Remove the pre-header text  "The Reports"

3) Change the header title "Publications"  to Our Research & Resources 

4) Update the Economic Impact Report title and text description to: 

Economic Impact Research

Update the text description to: Hoyt Advisory Services and Eigen10 Advisors research estimates the estimated how much apartments and their residents contribute to the economy at the national, state and local level.

5)  Update the Future Demand Report title and text description to  

Future Demand Research 

NMHC and NAA partnered with Hoyt Advisory Services to identify the demand for apartments through 2035. Download their analysis of the apartment industry.

6) This Future Demand Research is going to be split into 4 PDFs, so a little different than current set up.  It's OK if they are just text links, can we do 4 buttons, not sure how awkward that might look... OR maybe text links for 3 of them and button for full report? The PDFs we will have are: 
 
Download the Executive Summary
Download the National Report
Download the 50-Markets Report
Download the Full Report

7) Update the Vision 2030 title and text description to: 

Policies that Work 
Solutions to help build the housing the nation needs are out there but need to be more broadly adopted across the country.  They include reducing barriers to apartment construction, reforming land-use and zoning regulations, reducing parking requirements, and creating more public-private partnerships.

**Comment by m3ssij3ssi** [comment]
@acidjazz  - here's a mock up of what I think would look best for refactoring this:

![three links_1button](https://user-images.githubusercontent.com/47862779/177391051-bc5e461f-ebcd-4061-a0ec-bfedd03e916e.jpg)

the link color can either be the purple (which i pulled from the website 

Purple #624296 OR orange #FC763F 

let me know what you think. I think this would be the most straight forward way of refactoring this.

**Comment by m3ssij3ssi** [comment]
Here is the new PDF file for the "**Policies that Work**" block -
[Policy Recommendations Vision 2035.pdf](https://github.com/acidjazz/waa/files/9048784/Policy.Recommendations.Vision.2035.pdf)

**Comment by acidjazz** [comment]
- move resources to the top with we can do this 
- stay with the white
- follow mockup

**Comment by m3ssij3ssi** [comment]
@acidjazz thanks for the first pass - i think we're looking good- but a few quick things.
1) The yellow publication further down can be completely removed. 
2) For the listing of the Future Demand Research - please update to the following 

![Image](https://user-images.githubusercontent.com/47862779/177620811-279acbae-2ec0-43b0-a965-338e2bc1e9bd.png)

Basically remove the 4th bullet, and update the text in the button to say "Download Full Report PDF"

**Comment by m3ssij3ssi** [comment]
Saw edit was made! one more design tweak:

The spacing between the end of the text and the download button on the columns are uneven. see screenshot below. the first column has a lot of space between text and a download button, 3rd column has very little. 2nd column is just right. can we base the spacing on the second column?  thanks! 



![Image](https://user-images.githubusercontent.com/47862779/177650699-cf8ec344-e4d1-4d4c-b73e-cde33a012b68.png)

**Comment by acidjazz** [comment]
> Saw edit was made! one more design tweak:
> 
> The spacing between the end of the text and the download button on the columns are uneven. see screenshot below. the first column has a lot of space between text and a download button, 3rd column has very little. 2nd column is just right. can we base the spacing on the second column? thanks!
> 
> ![Image](https://user-images.githubusercontent.com/47862779/177650699-cf8ec344-e4d1-4d4c-b73e-cde33a012b68.png)

on its way to staging!

**Comment by m3ssij3ssi** [comment]
Sorry a couple of additional edits to the a links under Future Demand Research - see screenshot for what the changes should look like.  

1. Link text for Download National Report  - change to "Download National Report (Only)" 
2. Link text for Download 50-Markets - change to "Download 50-Metros Report (Only)"
3.  Change button for Full Download to say: Download Full Report PDF (National Report +50 Metros)
      -break the button text into two lines as shown in screenshot. 


![Image](https://user-images.githubusercontent.com/47862779/177871720-e8246003-6f71-40d4-8434-5caee976f531.png)

**Comment by m3ssij3ssi** [comment]
Wanted to follow up on this comment - this file is finalized so if you can link it that would be great - this if for the Policies that Work block

https://github.com/acidjazz/waa/issues/203#issuecomment-1175389404

**Comment by m3ssij3ssi** [comment]
Thanks for the changes to the button! One text changed was missed  - see screen shot below. It should say 50-Metros. Not markets. 


![Image](https://user-images.githubusercontent.com/47862779/177906814-d29fcf35-8a48-4846-9e0a-0f8bb6cba330.png)
