### ISSUE TITLE
District Changes

### ISSUE THREAD

**Issue by acidjazz** [acidjazz/waa#236]
Remove the following districts:

California District 40
Illinois District 18
Michigan District 4
New York District 22
Ohio District 13
Pennsylvania District 12
West Virginia District 2

For the following districts, we need to find a place to put this text:

"This area was redistricted in 2022.  The information included herein is reflective of the previous district data."

 It needs to show on both the webpage for the district numbers AND the PDF print out:

Florida District 5
Montana District 1
North Carolina District 5, 8, 9 and 13

![image](https://user-images.githubusercontent.com/967369/228923463-1be008e7-37b1-491c-a232-34d83f83e5e5.png)

**Comment by m3ssij3ssi** [comment]
this was in in 2023
